FORMAT: A1

# Group Store

## Stores collection [/stores]

### Returns all stores [GET]

+ Request List all stores

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json

    + Body

        [
          {
            "id": "fff26b63-ee68-4cde-9acf-7ff39ca6fa9e",
            "key": "haag",
            "name": "Feest-Pagac",
            "address": "9770 Wade Common",
            "country": "CD",
            "created_at": "2017-12-29T23:09:57.529Z",
            "updated_at": "2017-12-29T23:09:57.529Z"
          }
        ]
