FORMAT: A1

# Group Authentication

## Authentication [/auth]

+ Parameters
  + email (required) - User&#39;s email
  + password (required) - User&#39;s password
  + password_confirmation (required) - User&#39;s password confirmation
  + confirm_success_url (required) - URL to redirect to on email confirmation

### Delete current user [DELETE]

+ Request Delete current user (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: FsSoplNUWCRCn_Gan2zuhQ
        Token-Type: Bearer
        Client: YPZfZ5WwpqDmsAG_6wc0sQ
        Expiry: 1517575560
        Uid: ruthe.reilly@pfannerstillorn.org

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json

    + Body

        {
          "status": "success",
          "message": "Account with UID 'ruthe.reilly@pfannerstillorn.org' has been destroyed."
        }

### Sign up user [POST]

+ Request Sign up user (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json

    + Body

        {
          "email": "roy@labadiefahey.io",
          "password": "AfVhWzPo00Wh5sQf",
          "password_confirmation": "AfVhWzPo00Wh5sQf",
          "confirm_success_url": "http://vandervortdamore.net/clay"
        }

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json

    + Body

        {
          "status": "success",
          "data": {
            "id": "9ecd9359-4dd3-4e35-aa9c-501073af3141",
            "provider": "email",
            "uid": "roy@labadiefahey.io",
            "firstname": null,
            "email": "roy@labadiefahey.io",
            "created_at": "2018-01-19T12:46:00.064Z",
            "updated_at": "2018-01-19T12:46:00.064Z",
            "lastname": null
          }
        }

### Update current user [PATCH]

+ Request Update current user (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: LQfuDDoXMgJSPdWc4aEaXQ
        Token-Type: Bearer
        Client: Imjf21mPaDy5wzn3n2Evng
        Expiry: 1517575560
        Uid: louvenia_anderson@schmeler.com

    + Body

        {
          "password": "Q3H3V59oL25i",
          "password_confirmation": "Q3H3V59oL25i"
        }

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json

    + Body

        {
          "status": "success",
          "data": {
            "id": "947b2ac8-9558-4667-8927-2353ef4608a6",
            "email": "louvenia_anderson@schmeler.com",
            "provider": "email",
            "uid": "louvenia_anderson@schmeler.com",
            "firstname": "Conrad",
            "created_at": "2018-01-19T12:46:00.827Z",
            "updated_at": "2018-01-19T12:46:00.899Z",
            "lastname": "Streich"
          }
        }

## User session [auth/sign_in]

+ Parameters
  + email (required) - User&#39;s email
  + password (required) - User&#39;s password

### Sign in user [POST]

+ Request Sign in user (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json

    + Body

        {
          "email": "abagail.mann@hansenolson.com",
          "password": "6cGsFz5pL"
        }

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: XVpro2B_424yN0plR8aU9g
        token-type: Bearer
        client: jhn1AYqqX5Y32NHL6yI-jQ
        expiry: 1517575561
        uid: abagail.mann@hansenolson.com

    + Body

        {
          "data": {
            "id": "e4386d2f-0f84-4dbd-9c15-bf7d712f082d",
            "email": "abagail.mann@hansenolson.com",
            "provider": "email",
            "uid": "abagail.mann@hansenolson.com",
            "firstname": "Alan",
            "lastname": "Koepp"
          }
        }

## User session [auth/sign_out]

### Sign out user [DELETE]

+ Request Sign out user (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: L2eQfT13V4FVi7N7rZCQCw
        Token-Type: Bearer
        Client: 7kz_s9lUHwvNo1lVlReLIA
        Expiry: 1517575561
        Uid: damon_bauch@denesik.net

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json

    + Body

        {
          "success": true
        }

## User password [auth/password]

+ Parameters
  + password (required) - User&#39;s new password
  + password_confirmation (required) - User&#39;s new password confirmation

### Update current user&#39;s password [PATCH]

+ Request Update current user&#39;s password (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: nXIr9jASVVfp_yDH0ItBgw
        Token-Type: Bearer
        Client: 4CbJcpg4bIxibBMxnFsskw
        Expiry: 1517575561
        Uid: augustine@harris.io

    + Body

        {
          "password": "ZpBi6bV88sB97b2",
          "password_confirmation": "ZpBi6bV88sB97b2"
        }

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json

    + Body

        {
          "success": true,
          "data": {
            "id": "623f946f-bab9-4ae9-8abc-342867252ddb",
            "provider": "email",
            "email": "augustine@harris.io",
            "uid": "augustine@harris.io",
            "firstname": "Nils",
            "created_at": "2018-01-19T12:46:01.440Z",
            "updated_at": "2018-01-19T12:46:01.512Z",
            "lastname": "Schowalter"
          },
          "message": "Your password has been successfully updated."
        }

## User session [auth/validate_token]

### Validate user session [GET]

+ Request Validate user session (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: CMw45K4sGxAP_CoSrBoS3g
        Token-Type: Bearer
        Client: T6Z8xsEVZPC3r0QvYzYogA
        Expiry: 1517575561
        Uid: arvid.spinka@romaguera.name

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json

    + Body

        {
          "success": true,
          "data": {
            "id": "a21c3e76-b3d5-4211-956a-802d0fdd9185",
            "provider": "email",
            "uid": "arvid.spinka@romaguera.name",
            "firstname": "Hilton",
            "email": "arvid.spinka@romaguera.name",
            "lastname": "Kerluke"
          }
        }

# Group Categories

## Categories collection [/categories]

+ Parameters
  + label (required) - Category&#39;s label
  + tva (required) - Category&#39;s TVA rate
  + store_id (required) - Category&#39;s store id

### Create a category [POST]

+ Request Create a category (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: UvhEuhejeOxFZnV-nq_vvg
        Token-Type: Bearer
        Client: Qz7YGrOyjFTS0XJNfMu6Hw
        Expiry: 1517575561
        Uid: gardner.greenfelder@breitenberg.net

    + Body

        {
          "category": {
            "label": "Category label",
            "tva": "standard_rate",
            "store_id": "0f66c88e-8ebf-477d-ad1c-d448d8939dd4"
          }
        }

+ Response 201 (application/json)

    + Headers

        Content-Type: application/json

    + Body

        {
          "id": "58795d41-690e-407a-a440-92fdd70b7b22",
          "label": "Category label",
          "tva": "standard_rate",
          "store_id": "0f66c88e-8ebf-477d-ad1c-d448d8939dd4",
          "category_id": null,
          "created_at": "2018-01-19T12:46:02.078Z",
          "updated_at": "2018-01-19T12:46:02.078Z"
        }

### Returns all categories [GET]

+ Request List all categories (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: hF0f_GcHqGuaeoRxzWVtWw
        Token-Type: Bearer
        Client: kzbgf9Vm0YOTBvuROMua9g
        Expiry: 1517575561
        Uid: florida@grimes.io

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json

    + Body

        [
          {
            "id": "4035f9ba-2804-4204-9c70-1f63ea0ba8bb",
            "label": "Category label",
            "tva": "standard_rate",
            "store_id": "d6a5fefa-2266-4288-9710-5269f2936c04",
            "category_id": null,
            "created_at": "2018-01-19T12:46:01.706Z",
            "updated_at": "2018-01-19T12:46:01.706Z"
          }
        ]

## Single category [/categories/:id]

+ Parameters
  + label (required) - Category&#39;s name
  + tva (required) - Category&#39;s TVA rate

### Get a specific category [GET]

+ Request Getting a category (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: mFuAbsJEOh_nNDLjTM6lvA
        Token-Type: Bearer
        Client: 5CVmnv0T0hDTGd8LTTbRrw
        Expiry: 1517575562
        Uid: axel.herman@ruelryan.net

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json

    + Body

        {
          "id": "fe61a2d2-f174-4760-816c-989d6ec85de3",
          "label": "Category label",
          "tva": "standard_rate",
          "store_id": "5756c359-f155-420c-a4b0-bd177773fa26",
          "category_id": null,
          "created_at": "2018-01-19T12:46:02.167Z",
          "updated_at": "2018-01-19T12:46:02.167Z"
        }

### Update a specific category [PATCH]

+ Request Updating a category (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: AjpX51jy4d-3xXEylDVtXg
        Token-Type: Bearer
        Client: SeMye8fluE7K-VWNizPpcg
        Expiry: 1517575562
        Uid: brennon.strosin@baumbach.io

    + Body

        {
          "category": {
            "label": "Category label"
          }
        }

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json

    + Body

        {
          "id": "0ea1d324-3d81-419e-89f3-68fdbaf5a734",
          "store_id": "281089e8-9417-4c63-85a8-f38dc95f9d89",
          "label": "Category label",
          "tva": "standard_rate",
          "category_id": null,
          "created_at": "2018-01-19T12:46:02.328Z",
          "updated_at": "2018-01-19T12:46:02.328Z"
        }

# Group Manufacturers

## Manufacturers collection [/manufacturers]

+ Parameters
  + name (required) - Manufacturer&#39;s name
  + notes - Notes about manufacturer
  + store_id (required) - Manufacturer&#39;s store id

### Create a manufacturer [POST]

+ Request Create a manufacturer (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: AbLYT0UPBQIwwxNaA2KMAg
        Token-Type: Bearer
        Client: fGF9apgrU-cysqMzbXwyqQ
        Expiry: 1517575562
        Uid: chadrick_dare@schmitt.org

    + Body

        {
          "manufacturer": {
            "name": "Aragog",
            "notes": "466 Elva Row",
            "store_id": "a870f8a0-6626-4720-802c-53ce3a9d637a"
          }
        }

+ Response 201 (application/json)

    + Headers

        Content-Type: application/json

    + Body

        {
          "id": "824bbf21-bfc0-4d0a-a23e-7afc0428d336",
          "name": "Aragog",
          "notes": "466 Elva Row",
          "store_id": "a870f8a0-6626-4720-802c-53ce3a9d637a",
          "created_at": "2018-01-19T12:46:02.803Z",
          "updated_at": "2018-01-19T12:46:02.803Z"
        }

### Returns all manufacturers [GET]

+ Request List all manufacturers (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: F6tcIBZtqiq8-R72Wv-4cQ
        Token-Type: Bearer
        Client: 1g7m8z4NbnKIw_F7AsXheA
        Expiry: 1517575562
        Uid: conner.jerde@heidenreich.net

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json

    + Body

        [
          {
            "id": "16d93b68-95d2-4a41-8443-25d1b1f88b72",
            "name": "Cormac McLaggen",
            "notes": "8482 Mortimer Terrace",
            "store_id": "8ee2d9ca-22b3-4cfd-b28d-9e3a7b5913a5",
            "created_at": "2018-01-19T12:46:02.510Z",
            "updated_at": "2018-01-19T12:46:02.510Z"
          }
        ]

## Single manufacturer [/manufacturers/:id]

+ Parameters
  + name (required) - Manufacturer&#39;s name
  + notes - Notes about manufacturer

### Get a specific manufacturer [GET]

+ Request Getting a manufacturer (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: 68gd1ePip5lJB6ajNrvhbA
        Token-Type: Bearer
        Client: u7_M6uLxCnVWHB4iWIUDJA
        Expiry: 1517575562
        Uid: vernie@dare.io

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json

    + Body

        {
          "id": "2fef6d00-c656-49e3-95da-95fed464e48e",
          "name": "Molly Weasley",
          "notes": "1285 Zelma Throughway",
          "store_id": "99f35ca9-d19a-4954-bcbe-5d36198387a1",
          "created_at": "2018-01-19T12:46:02.841Z",
          "updated_at": "2018-01-19T12:46:02.841Z"
        }

### Update a specific manufacturer [PATCH]

+ Request Updating a manufacturer (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: WXDsZ6GJyBa12dBs7QoWYQ
        Token-Type: Bearer
        Client: I2i43wRMOBJEX0GXJAxS_w
        Expiry: 1517575563
        Uid: keyon@oberbrunner.com

    + Body

        {
          "manufacturer": {
            "name": "Arthur Weasley"
          }
        }

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json

    + Body

        {
          "id": "a1b2fe7f-8a2f-42c3-9b15-9a119f82ce8a",
          "store_id": "ee7b0293-06d3-4bbc-b22a-cdf401ddbbf6",
          "name": "Arthur Weasley",
          "notes": "970 Adams Ville",
          "created_at": "2018-01-19T12:46:03.005Z",
          "updated_at": "2018-01-19T12:46:03.148Z"
        }

# Group Providers

## Providers collection [/providers]

+ Parameters
  + name (required) - Provider&#39;s name
  + notes - Notes about provider
  + store_id (required) - Provider&#39;s store id

### Create a provider [POST]

+ Request Create a provider (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: 420GTXXwcTpgxrgynCvPPQ
        Token-Type: Bearer
        Client: ocJWq22W6d1VyFKB34rb6w
        Expiry: 1517575563
        Uid: shannon_bauch@sengernienow.biz

    + Body

        {
          "provider": {
            "name": "Krombopulos Michael",
            "notes": "663 Don Glens",
            "store_id": "bddb9353-9269-4786-b3c9-936db6486f20"
          }
        }

+ Response 201 (application/json)

    + Headers

        Content-Type: application/json

    + Body

        {
          "id": "96874d0d-16ba-41af-8d6c-25d954699d2e",
          "name": "Krombopulos Michael",
          "notes": "663 Don Glens",
          "store_id": "bddb9353-9269-4786-b3c9-936db6486f20",
          "created_at": "2018-01-19T12:46:03.533Z",
          "updated_at": "2018-01-19T12:46:03.533Z"
        }

### Returns all providers [GET]

+ Request List all providers (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: EmgvNUKwd4RreBlEFx6Fcg
        Token-Type: Bearer
        Client: df5IgDWO2jenEdH65TJVQA
        Expiry: 1517575563
        Uid: manley_reilly@effertz.com

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json

    + Body

        [
          {
            "id": "3f54d541-c72e-4477-bf2a-9552cc5463d4",
            "name": "Arthricia",
            "notes": "8954 Parker Spring",
            "store_id": "fc433783-bf2f-48d6-ac00-264a1edd2523",
            "created_at": "2018-01-19T12:46:03.219Z",
            "updated_at": "2018-01-19T12:46:03.219Z"
          }
        ]

## Single provider [/providers/:id]

+ Parameters
  + name (required) - Provider&#39;s name
  + notes - Notes about provider

### Get a specific provider [GET]

+ Request Getting a provider (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: hPvVfcUhc7dXX6JiYWsSXg
        Token-Type: Bearer
        Client: KCN6w8g2i31xeDkxbpEhJw
        Expiry: 1517575563
        Uid: maximillian@cartwright.org

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json

    + Body

        {
          "id": "929988a1-ebad-4578-9bf5-66d61baf6547",
          "name": "Tammy Gueterman",
          "notes": "26845 Hattie Passage",
          "store_id": "7f636918-75a8-4b57-b678-bb37d39ff1c9",
          "created_at": "2018-01-19T12:46:03.565Z",
          "updated_at": "2018-01-19T12:46:03.565Z"
        }

### Update a specific provider [PATCH]

+ Request Updating a provider (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: sKQVWnmsP-Q_sMVVy2yEcw
        Token-Type: Bearer
        Client: 3JVg_R7ukwTmABdPRT3tFw
        Expiry: 1517575563
        Uid: kira.howell@armstrong.co

    + Body

        {
          "provider": {
            "name": "Abradolf Lincler"
          }
        }

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json

    + Body

        {
          "id": "2abb4e08-2dbf-4def-85f5-7dc9552eb9ef",
          "store_id": "21ad0066-6508-465e-85bc-90df1cff3b2e",
          "name": "Abradolf Lincler",
          "notes": "48666 Damien Drives",
          "created_at": "2018-01-19T12:46:03.729Z",
          "updated_at": "2018-01-19T12:46:03.920Z"
        }

# Group Store Memberships

## Store memberships collection [/store_memberships]

+ Parameters
  + user_id (required) - Membership&#39;s user
  + store_id (required) - Membership&#39;s store
  + role (required) - Membership&#39;s role (regular, admin, owner)

### Create a store membership [POST]

+ Request Create a store membership (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: V9cS3G9_ec9uK6gr_Az2bg
        Token-Type: Bearer
        Client: CYik6sFNCWkQHsdd7Qf4Ww
        Expiry: 1517575564
        Uid: jovan.fahey@wilkinson.biz

    + Body

        {
          "store_membership": {
            "user_id": "29c52473-9c4b-468a-a758-0e526c83470f",
            "store_id": "33c14b93-63be-49f6-a7ac-a0803a437b1e",
            "role": "regular"
          }
        }

+ Response 201 (application/json)

    + Headers

        Content-Type: application/json

    + Body

        {
          "id": "9f59ed88-e80f-41c3-8169-ff875d8a6950",
          "store_id": "33c14b93-63be-49f6-a7ac-a0803a437b1e",
          "user_id": "29c52473-9c4b-468a-a758-0e526c83470f",
          "role": "regular",
          "created_at": "2018-01-19T12:46:04.304Z",
          "updated_at": "2018-01-19T12:46:04.304Z"
        }

### Returns all store memberships [GET]

+ Request List all store memberships (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: j7MjlPQUT9L3gyGLqLvCZA
        Token-Type: Bearer
        Client: -gMq1-NV1h2mnM0x70WSNg
        Expiry: 1517575564
        Uid: aida@wilkinson.co

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json

    + Body

        [
          {
            "id": "258318bc-4b5b-4e68-9a33-83d12078d03b",
            "store_id": "c2aeb099-b05b-403a-ace8-22ea3a49a4be",
            "user_id": "8ce6f65b-e642-42ff-8f02-532b965c284e",
            "role": "admin",
            "created_at": "2018-01-19T12:46:03.952Z",
            "updated_at": "2018-01-19T12:46:03.952Z"
          }
        ]

## Single store membership [/store_memberships/:id]

+ Parameters
  + role (required) - Membership&#39;s role (regular, admin, owner)

### Delete a specific store membership [DELETE]

+ Request Deleting a store membership (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: jPWIR_hvruhmhgdPHG4ajQ
        Token-Type: Bearer
        Client: uCpYBPxLl6i-2UvATtUVMg
        Expiry: 1517575564
        Uid: kyler@simoniskemmer.io

+ Response 204 ()

### Get a specific store membership [GET]

+ Request Getting a store membership (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: 7W4jwh-csoiBnWdyGSIztQ
        Token-Type: Bearer
        Client: RqCkecUXlk77aGKWtoUbwA
        Expiry: 1517575564
        Uid: eleanore.lockman@dietrich.com

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json

    + Body

        {
          "id": "cf1a8957-52ab-4563-bc7f-f4fd9763be26",
          "store_id": "6eca6c28-5340-4823-a87c-464cdd64b3c7",
          "user_id": "90489a01-48f5-4cf4-b2b3-f99982451d6f",
          "role": "regular",
          "created_at": "2018-01-19T12:46:04.354Z",
          "updated_at": "2018-01-19T12:46:04.354Z"
        }

### Update a specific store membership [PATCH]

+ Request Updating a store membership (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: zrLeg_LlPr82B8y9ZDgg5A
        Token-Type: Bearer
        Client: 9aX8O59Zgi7lNBkMSE7U5w
        Expiry: 1517575564
        Uid: andreane@bernhard.biz

    + Body

        {
          "store_membership": {
            "role": "admin"
          }
        }

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json

    + Body

        {
          "id": "efd94bf9-4455-4725-9446-fbde84ef95a2",
          "store_id": "8c3baca2-42cc-4d02-9bd7-dc5fc559d0d3",
          "role": "admin",
          "user_id": "74a09a87-eea2-4c4d-a15b-0739daf83793",
          "created_at": "2018-01-19T12:46:04.530Z",
          "updated_at": "2018-01-19T12:46:04.677Z"
        }

# Group Stores

## Stores collection [/stores]

+ Parameters
  + name (required) - Store&#39;s name
  + address - Store&#39;s address
  + country (required) - Store&#39;s country
  + key (required) - Store&#39;s key

### Create a store [POST]

+ Request Create a store (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: dx1k8mN3VpOgtxspoisEWg
        Token-Type: Bearer
        Client: 6fVCjGumnhd9iKuih2TOkQ
        Expiry: 1517575565
        Uid: bella@reichel.info

    + Body

        {
          "store": {
            "name": "Utapau",
            "address": "5380 Schoen Circle",
            "country": "MQ",
            "key": "utapau-26"
          }
        }

+ Response 201 (application/json)

    + Headers

        Content-Type: application/json

    + Body

        {
          "id": "ebf3d608-f794-4a34-aedf-8567f2c195f4",
          "key": "utapau-26",
          "name": "Utapau",
          "address": "5380 Schoen Circle",
          "country": "MQ",
          "created_at": "2018-01-19T12:46:05.183Z",
          "updated_at": "2018-01-19T12:46:05.183Z"
        }

### Returns all stores [GET]

+ Request List all stores (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: _ortRKmUd_f5O4a_vT6Drg
        Token-Type: Bearer
        Client: Tfx9pFYdNVIT0mxMxl1k5w
        Expiry: 1517575564
        Uid: jayda_koepp@moriettestanton.co

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json

    + Body

        [
          {
            "id": "d941c059-8945-4fde-85af-cbc802b581de",
            "key": "lothal-25",
            "name": "Lothal",
            "address": "46633 Maybelle Forest",
            "country": "BY",
            "created_at": "2018-01-19T12:46:04.875Z",
            "updated_at": "2018-01-19T12:46:04.875Z"
          }
        ]

## Single store [/stores/:id]

+ Parameters
  + name (required) - Store&#39;s name
  + address - Store&#39;s address
  + country (required) - Store&#39;s country

### Get a specific store [GET]

+ Request Getting a store (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: NprGkWyp3oXtEtajAwN5vw
        Token-Type: Bearer
        Client: fEMBvz6mhUXJdUr1WjlBNA
        Expiry: 1517575565
        Uid: harrison@kris.io

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json

    + Body

        {
          "id": "0fdf029b-7648-4df1-8494-32b4f7330740",
          "key": "lothal-28",
          "name": "Lothal",
          "address": "52100 Rosie Green",
          "country": "RU",
          "created_at": "2018-01-19T12:46:05.208Z",
          "updated_at": "2018-01-19T12:46:05.208Z"
        }

### Update a specific store [PATCH]

+ Request Updating a store (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: VU4gIA_mCOLj7XHMoaA3pw
        Token-Type: Bearer
        Client: Z2vwCSuc3fDXtTI7RMmgHA
        Expiry: 1517575565
        Uid: deron@leannon.info

    + Body

        {
          "store": {
            "name": "Sullust"
          }
        }

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json

    + Body

        {
          "id": "fc239fd7-0f7b-4b87-941d-8ba1f5a197f2",
          "name": "Sullust",
          "country": "PK",
          "key": "takodana-29",
          "address": "2700 Bechtelar Passage",
          "created_at": "2018-01-19T12:46:05.377Z",
          "updated_at": "2018-01-19T12:46:05.536Z"
        }
