FORMAT: A1

# Group Authentication

## Authentication [/auth]

+ Parameters
  + email (required) - User&#39;s email
  + password (required) - User&#39;s password
  + password_confirmation (required) - User&#39;s password confirmation
  + confirm_success_url (required) - URL to redirect to on email confirmation

### Delete current user [DELETE]

+ Request Delete current user (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: 96UHf68oRQ7pJevpb9TNaw
        Token-Type: Bearer
        Client: U0vAmyiRlqxQTUMDmf0kng
        Expiry: 1519912497
        Uid: samantha.turcotte@lakin.biz

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json

    + Body

        {
          "status": "success",
          "message": "Account with UID 'samantha.turcotte@lakin.biz' has been destroyed."
        }

### Sign up user [POST]

+ Request Sign up user (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json

    + Body

        {
          "email": "morris@morar.io",
          "password": "3nJiXv3eQuNzGiCy",
          "password_confirmation": "3nJiXv3eQuNzGiCy",
          "confirm_success_url": "http://welch.info/verla_parisian"
        }

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json

    + Body

        {
          "status": "success",
          "data": {
            "id": "d119288f-aeed-44fb-813b-30e53d8f7f85",
            "provider": "email",
            "uid": "morris@morar.io",
            "firstname": null,
            "email": "morris@morar.io",
            "created_at": "2018-02-01T13:54:56.806Z",
            "updated_at": "2018-02-01T13:54:56.806Z",
            "lastname": null,
            "locale": "en"
          }
        }

### Update current user [PATCH]

+ Request Update current user (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: iwov-4IIZU_qpvRb0MyNAQ
        Token-Type: Bearer
        Client: X_auNi1b-T9DCvLwVBZ-8Q
        Expiry: 1519912497
        Uid: tabitha@lang.co

    + Body

        {
          "password": "2uEiR7Op7hYfHeI",
          "password_confirmation": "2uEiR7Op7hYfHeI"
        }

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: iwov-4IIZU_qpvRb0MyNAQ
        token-type: Bearer
        client: X_auNi1b-T9DCvLwVBZ-8Q
        expiry: 1519912497
        uid: tabitha@lang.co

    + Body

        {
          "status": "success",
          "data": {
            "id": "24730d6e-2791-4424-945c-32b7d6a1c504",
            "email": "tabitha@lang.co",
            "provider": "email",
            "uid": "tabitha@lang.co",
            "firstname": "Nora",
            "created_at": "2018-02-01T13:54:57.485Z",
            "updated_at": "2018-02-01T13:54:57.561Z",
            "lastname": "Beatty",
            "locale": "en"
          }
        }

## User session [auth/sign_in]

+ Parameters
  + email (required) - User&#39;s email
  + password (required) - User&#39;s password

### Sign in user [POST]

+ Request Sign in user (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json

    + Body

        {
          "email": "paula_walsh@ankundingromaguera.io",
          "password": "YeJv0b5o0c"
        }

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: zXcmDRIhvbQGExbWrMfZWg
        token-type: Bearer
        client: KJyhEAJVQvYX52XT8U8I5A
        expiry: 1519912497
        uid: paula_walsh@ankundingromaguera.io

    + Body

        {
          "data": {
            "id": "2bce4a77-8d45-4e2f-b3aa-088b54631267",
            "email": "paula_walsh@ankundingromaguera.io",
            "provider": "email",
            "uid": "paula_walsh@ankundingromaguera.io",
            "firstname": "Josie",
            "lastname": "Kling",
            "locale": "en"
          }
        }

## User session [auth/sign_out]

### Sign out user [DELETE]

+ Request Sign out user (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: 9y0tya1ZVC50EuNxO8VX9A
        Token-Type: Bearer
        Client: xGvk_BKTIwTPao2sapEnVA
        Expiry: 1519912497
        Uid: jan@block.biz

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json

    + Body

        {
          "success": true
        }

## User password [auth/password]

+ Parameters
  + password (required) - User&#39;s new password
  + password_confirmation (required) - User&#39;s new password confirmation

### Update current user&#39;s password [PATCH]

+ Request Update current user&#39;s password (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: HBT4zJo3Q9mTgnBl29BP4A
        Token-Type: Bearer
        Client: r-56XNghkMicX6prjzeDsA
        Expiry: 1519912498
        Uid: frederick@westcollier.org

    + Body

        {
          "password": "7uIa1zZq",
          "password_confirmation": "7uIa1zZq"
        }

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: HBT4zJo3Q9mTgnBl29BP4A
        token-type: Bearer
        client: r-56XNghkMicX6prjzeDsA
        expiry: 1519912498
        uid: frederick@westcollier.org

    + Body

        {
          "success": true,
          "data": {
            "id": "02ebee86-0840-4888-ab9d-1a8167670f69",
            "provider": "email",
            "email": "frederick@westcollier.org",
            "uid": "frederick@westcollier.org",
            "firstname": "Eliezer",
            "created_at": "2018-02-01T13:54:58.166Z",
            "updated_at": "2018-02-01T13:54:58.262Z",
            "lastname": "Bogan",
            "locale": "en"
          },
          "message": "Your password has been successfully updated."
        }

## User session [auth/validate_token]

### Validate user session [GET]

+ Request Validate user session (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: JMdmTEd7qwyO2Xaj-jjQZQ
        Token-Type: Bearer
        Client: Hll3j9MPi9h0xhJzqsublA
        Expiry: 1519912497
        Uid: lavern.hammes@dietrich.io

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: JMdmTEd7qwyO2Xaj-jjQZQ
        token-type: Bearer
        client: Hll3j9MPi9h0xhJzqsublA
        expiry: 1519912497
        uid: lavern.hammes@dietrich.io

    + Body

        {
          "success": true,
          "data": {
            "id": "2b619864-f1b8-4903-8fdd-00785e78808f",
            "provider": "email",
            "uid": "lavern.hammes@dietrich.io",
            "firstname": "Gina",
            "email": "lavern.hammes@dietrich.io",
            "lastname": "Feil",
            "locale": "en"
          }
        }

# Group Categories

## Categories collection [/categories]

+ Parameters
  + name (required) - Category&#39;s name
  + tva (required) - Category&#39;s TVA rate
  + store_id (required) - Category&#39;s store id

### Create a category [POST]

+ Request Create a category (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: WcAt-whDSKSj_rf8vGg08w
        Token-Type: Bearer
        Client: 4raUjdgcmi3rZPrpUhFsiQ
        Expiry: 1519912498
        Uid: okey.ortiz@kunde.co

    + Body

        {
          "category": {
            "name": "Merican Ale",
            "tva": "parking_rate",
            "store_id": "b189b433-c144-47e7-963c-23f4448823e9"
          }
        }

+ Response 201 (application/json)

    + Headers

        Content-Type: application/json
        access-token: WcAt-whDSKSj_rf8vGg08w
        token-type: Bearer
        client: 4raUjdgcmi3rZPrpUhFsiQ
        expiry: 1519912498
        uid: okey.ortiz@kunde.co

    + Body

        {
          "id": "604095c2-164f-4834-95c6-f05d60e5fedb",
          "name": "Merican Ale",
          "tva": "parking_rate",
          "store_id": "b189b433-c144-47e7-963c-23f4448823e9",
          "category_id": null,
          "created_at": "2018-02-01T13:54:58.864Z",
          "updated_at": "2018-02-01T13:54:58.864Z"
        }

### Returns all categories [GET]

+ Request List all categories (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: 917mvohL1SYdg3Bw3urDRA
        Token-Type: Bearer
        Client: t1TZiOC6Sads52SDoJcrEg
        Expiry: 1519912498
        Uid: kattie_yost@wiza.name

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: 917mvohL1SYdg3Bw3urDRA
        token-type: Bearer
        client: t1TZiOC6Sads52SDoJcrEg
        expiry: 1519912498
        uid: kattie_yost@wiza.name

    + Body

        [
          {
            "id": "4faf7227-e77d-4998-859c-7ff0a8b5d44b",
            "name": "Sour Ale",
            "tva": "standard_rate",
            "store_id": "3dcaa164-203a-4ff8-9cd7-805631538ee4",
            "category_id": null,
            "created_at": "2018-02-01T13:54:58.457Z",
            "updated_at": "2018-02-01T13:54:58.457Z"
          }
        ]

## Single category [/categories/:id]

+ Parameters
  + name (required) - Category&#39;s name
  + tva (required) - Category&#39;s TVA rate

### Get a specific category [GET]

+ Request Getting a category (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: mxPe6qFFdlni6E7664BGQw
        Token-Type: Bearer
        Client: Mtq7hrh3zhxfOfIdseZtMA
        Expiry: 1519912498
        Uid: electa.kuhic@dubuque.biz

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: mxPe6qFFdlni6E7664BGQw
        token-type: Bearer
        client: Mtq7hrh3zhxfOfIdseZtMA
        expiry: 1519912498
        uid: electa.kuhic@dubuque.biz

    + Body

        {
          "id": "f629df6b-d0df-4cda-9e02-f03e1170c4c9",
          "name": "English Pale Ale",
          "tva": "standard_rate",
          "store_id": "46fc1673-8791-4681-a19f-34b15d382525",
          "category_id": null,
          "created_at": "2018-02-01T13:54:58.908Z",
          "updated_at": "2018-02-01T13:54:58.908Z"
        }

### Update a specific category [PATCH]

+ Request Updating a category (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: 6Pqj4mT2FO4Q8h8NjxbcBg
        Token-Type: Bearer
        Client: gGLeAHXh0BCGNG-UMItyWw
        Expiry: 1519912499
        Uid: amelia@dicki.com

    + Body

        {
          "category": {
            "name": "Bock"
          }
        }

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: 6Pqj4mT2FO4Q8h8NjxbcBg
        token-type: Bearer
        client: gGLeAHXh0BCGNG-UMItyWw
        expiry: 1519912499
        uid: amelia@dicki.com

    + Body

        {
          "id": "1f403cc8-3b13-4c64-9454-e9d938fc0220",
          "store_id": "af00952d-b10a-4385-982f-a36977be210d",
          "name": "Bock",
          "tva": "parking_rate",
          "category_id": null,
          "created_at": "2018-02-01T13:54:59.113Z",
          "updated_at": "2018-02-01T13:54:59.287Z"
        }

# Group Custom Attributes

## Custom Attributes collection [/custom_attributes]

+ Parameters
  + name (required) - Custom Attribute&#39;s name
  + type (required) - Custom Attribute&#39;s type (text, number)
  + store_id (required) - Custom Attribute&#39;s store id

### Create a custom attribute [POST]

+ Request Create a custom attribute (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: nBKQYhzwFS8esJ016rydiQ
        Token-Type: Bearer
        Client: rovK6wfUIl7mT2A1Ed0jhw
        Expiry: 1519912499
        Uid: jairo@schultzgorczany.org

    + Body

        {
          "custom_attribute": {
            "name": "Mosaic",
            "type": "text",
            "store_id": "6d538421-aee6-4b7a-b668-94b8978b9794"
          }
        }

+ Response 201 (application/json)

    + Headers

        Content-Type: application/json
        access-token: nBKQYhzwFS8esJ016rydiQ
        token-type: Bearer
        client: rovK6wfUIl7mT2A1Ed0jhw
        expiry: 1519912499
        uid: jairo@schultzgorczany.org

    + Body

        {
          "id": "be4852a7-4ec8-4329-b0cb-e4bf642c8e72",
          "name": "Mosaic",
          "type": "text",
          "store_id": "6d538421-aee6-4b7a-b668-94b8978b9794",
          "created_at": "2018-02-01T13:54:59.688Z",
          "updated_at": "2018-02-01T13:54:59.688Z"
        }

### Returns all custom_attributes [GET]

+ Request List all custom attributes (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: tVdSzoU62cSpEYiS0rHVNA
        Token-Type: Bearer
        Client: kaf7hEFTmaaR5QA3Cx_Kvw
        Expiry: 1519912499
        Uid: elton_greenfelder@bartolettiruel.name

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: tVdSzoU62cSpEYiS0rHVNA
        token-type: Bearer
        client: kaf7hEFTmaaR5QA3Cx_Kvw
        expiry: 1519912499
        uid: elton_greenfelder@bartolettiruel.name

    + Body

        [
          {
            "id": "d0dc3135-c8dc-4e0a-b8f9-644a5a163cc1",
            "name": "Glacier",
            "type": "number",
            "store_id": "d62a2530-cc26-44af-a6d6-625616a14bf4",
            "created_at": "2018-02-01T13:54:59.348Z",
            "updated_at": "2018-02-01T13:54:59.348Z"
          }
        ]

## Single custom attribute [/custom_attributes/:id]

+ Parameters
  + name (required) - Custom Attribute&#39;s name
  + type (required) - Custom Attribute&#39;s type

### Delete a specific custom attribute [DELETE]

+ Request Deleting a custom attribute (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: sbF5buOy7a2lHePpOVuJbw
        Token-Type: Bearer
        Client: xa73CA5qID7cYaXyuCdX_g
        Expiry: 1519912500
        Uid: kaia_fritsch@stiedemann.name

+ Response 204 ()

    + Headers

        access-token: sbF5buOy7a2lHePpOVuJbw
        token-type: Bearer
        client: xa73CA5qID7cYaXyuCdX_g
        expiry: 1519912500
        uid: kaia_fritsch@stiedemann.name

### Get a specific custom attribute [GET]

+ Request Getting a custom attribute (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: NyDrMUQickR1sMwKpScjOQ
        Token-Type: Bearer
        Client: ZopuUc01xX6Q0Mu-5kAKtQ
        Expiry: 1519912499
        Uid: salma.metz@hirthetorphy.org

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: NyDrMUQickR1sMwKpScjOQ
        token-type: Bearer
        client: ZopuUc01xX6Q0Mu-5kAKtQ
        expiry: 1519912499
        uid: salma.metz@hirthetorphy.org

    + Body

        {
          "id": "85f862d2-e7e5-4573-9b0c-d19a5e9fefb4",
          "name": "Crystal",
          "type": "text",
          "store_id": "3fe7db36-fe21-4e42-93f2-f9a482063396",
          "created_at": "2018-02-01T13:54:59.729Z",
          "updated_at": "2018-02-01T13:54:59.729Z"
        }

### Update a specific custom attribute [PATCH]

+ Request Updating a custom_attribute (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: -PDzIfUkEyQF5lKkp-ALjg
        Token-Type: Bearer
        Client: Q6I29gGBH66u3RVJSI3NxQ
        Expiry: 1519912499
        Uid: jeramy@kubkonopelski.com

    + Body

        {
          "custom_attribute": {
            "name": "Galena"
          }
        }

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: -PDzIfUkEyQF5lKkp-ALjg
        token-type: Bearer
        client: Q6I29gGBH66u3RVJSI3NxQ
        expiry: 1519912499
        uid: jeramy@kubkonopelski.com

    + Body

        {
          "id": "b1311915-0503-4df3-a8c6-12b34dd9fbc9",
          "store_id": "23efc1a4-e9b4-469f-83c2-59433e179a67",
          "name": "Galena",
          "type": "text",
          "created_at": "2018-02-01T13:54:59.918Z",
          "updated_at": "2018-02-01T13:55:00.079Z"
        }

# Group Inventories

## Inventories collection [/inventories]

+ Parameters
  + store_id (required) - Inventory&#39;s store id

### Create a inventory [POST]

+ Request Create a inventory (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: 2DID9y77xU5JQh8MNSMEwg
        Token-Type: Bearer
        Client: PE_LQn8MIXYq46FEJIauWg
        Expiry: 1519912500
        Uid: aliza_steuber@wintheiser.biz

    + Body

        {
          "inventory": {
            "store_id": "f857eb56-d73b-4219-86f6-1f6eb3b64f50"
          }
        }

+ Response 201 (application/json)

    + Headers

        Content-Type: application/json
        access-token: 2DID9y77xU5JQh8MNSMEwg
        token-type: Bearer
        client: PE_LQn8MIXYq46FEJIauWg
        expiry: 1519912500
        uid: aliza_steuber@wintheiser.biz

    + Body

        {
          "id": "6e647962-ed3d-424f-afc0-1cca257f8a7b",
          "locked_at": null,
          "store_id": "f857eb56-d73b-4219-86f6-1f6eb3b64f50",
          "created_at": "2018-02-01T13:55:00.689Z",
          "updated_at": "2018-02-01T13:55:00.689Z"
        }

### Returns all inventories [GET]

+ Request List all inventories (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: 4AXliS0fXCWh3QSC7QMLpA
        Token-Type: Bearer
        Client: Hdtpnz-tI7XZF7izaJ9qFQ
        Expiry: 1519912500
        Uid: fern@wolf.biz

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: 4AXliS0fXCWh3QSC7QMLpA
        token-type: Bearer
        client: Hdtpnz-tI7XZF7izaJ9qFQ
        expiry: 1519912500
        uid: fern@wolf.biz

    + Body

        [
          {
            "id": "b70b563a-1999-407e-95bf-5990db951044",
            "locked_at": null,
            "store_id": "b63154ea-fa29-4609-8577-edb239953bba",
            "created_at": "2018-02-01T13:55:00.356Z",
            "updated_at": "2018-02-01T13:55:00.356Z"
          }
        ]

## Single inventory [/inventories/:id]

### Delete a specific inventory [DELETE]

+ Request Deleting a inventory (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: eXkDOKwNuvHEXWO8uKkggg
        Token-Type: Bearer
        Client: QYK96QJZh5K_L50FPy4Qvw
        Expiry: 1519912500
        Uid: paolo@marquardtschamberger.io

+ Response 204 ()

    + Headers

        access-token: eXkDOKwNuvHEXWO8uKkggg
        token-type: Bearer
        client: QYK96QJZh5K_L50FPy4Qvw
        expiry: 1519912500
        uid: paolo@marquardtschamberger.io

### Get a specific inventory [GET]

+ Request Getting a inventory (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: PHO0KdstY5urs7PcKXVxYw
        Token-Type: Bearer
        Client: 0XPB4JEWtxAKVFvPvcFrgw
        Expiry: 1519912500
        Uid: luther@koelpin.com

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: PHO0KdstY5urs7PcKXVxYw
        token-type: Bearer
        client: 0XPB4JEWtxAKVFvPvcFrgw
        expiry: 1519912500
        uid: luther@koelpin.com

    + Body

        {
          "id": "f11d0c79-5e22-4ade-a5f7-03a0cf394d02",
          "locked_at": null,
          "store_id": "149c066e-58d4-40b3-ba2c-19767f2ce646",
          "created_at": "2018-02-01T13:55:00.723Z",
          "updated_at": "2018-02-01T13:55:00.723Z"
        }

## Single inventory [/inventories/:id/lock]

### Lock a specific inventory [PATCH]

+ Request Locking a inventory (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: gxO_3IUIoah9WiCxG9lLEw
        Token-Type: Bearer
        Client: vYaCwGJxfJ2KPZPhDqt80g
        Expiry: 1519912501
        Uid: valerie_leffler@reillyturcotte.co

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: gxO_3IUIoah9WiCxG9lLEw
        token-type: Bearer
        client: vYaCwGJxfJ2KPZPhDqt80g
        expiry: 1519912501
        uid: valerie_leffler@reillyturcotte.co

    + Body

        {
          "id": "68588a89-edba-4291-9f30-367b303bab34",
          "store_id": "1d634807-a2bd-4095-ac7d-514c64601625",
          "locked_at": "2018-02-01T13:55:01.264Z",
          "created_at": "2018-02-01T13:55:01.100Z",
          "updated_at": "2018-02-01T13:55:01.265Z"
        }

# Group Inventory Variants

## Inventory variants collection [/inventory_variants]

+ Parameters
  + inventory_id (required) - Inventory variant&#39;s inventory id
  + variant_id (required) - Inventory variant&#39;s variant id
  + quantity (required) - Inventory variant&#39;s quantity

### Create an inventory variant [POST]

+ Request Create an inventory variant (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: 2asHQQig2Y8uY813J0Xobg
        Token-Type: Bearer
        Client: JzSKcwfynK8Zi6VnxS651Q
        Expiry: 1519912501
        Uid: wellington.walker@vonruedencarter.net

    + Body

        {
          "inventory_variant": {
            "inventory_id": "0433212b-9dc3-487a-9ef2-a597e5f3393d",
            "variant_id": "0ac83ae9-6cf8-4ea5-ac98-3a037016e75a",
            "quantity": 5
          }
        }

+ Response 201 (application/json)

    + Headers

        Content-Type: application/json
        access-token: 2asHQQig2Y8uY813J0Xobg
        token-type: Bearer
        client: JzSKcwfynK8Zi6VnxS651Q
        expiry: 1519912501
        uid: wellington.walker@vonruedencarter.net

    + Body

        {
          "id": "72f7215d-0688-4687-9102-45ddfe33ff7b",
          "quantity": 5,
          "inventory_id": "0433212b-9dc3-487a-9ef2-a597e5f3393d",
          "variant_id": "0ac83ae9-6cf8-4ea5-ac98-3a037016e75a",
          "created_at": "2018-02-01T13:55:01.846Z",
          "updated_at": "2018-02-01T13:55:01.846Z"
        }

### Returns all inventory_variants [GET]

+ Request List all inventory_variants (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: zI71n4lTfVfeqn9uPrd8aw
        Token-Type: Bearer
        Client: ayGtGUqrKTAeIEDzLiCijQ
        Expiry: 1519912501
        Uid: rex@considine.net

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: zI71n4lTfVfeqn9uPrd8aw
        token-type: Bearer
        client: ayGtGUqrKTAeIEDzLiCijQ
        expiry: 1519912501
        uid: rex@considine.net

    + Body

        [
          {
            "id": "6c67d628-bb99-4e27-8354-43d444c7aeef",
            "quantity": 598,
            "inventory_id": "69912be0-5dff-4025-be78-4effebf4b526",
            "variant_id": "120c4063-edb7-4871-93f7-e790388166c4",
            "created_at": "2018-02-01T13:55:01.445Z",
            "updated_at": "2018-02-01T13:55:01.445Z"
          }
        ]

## Single inventory variant [/inventory_variants/:id]

+ Parameters
  + quantity (required) - Inventory variant&#39;s quantity

### Delete a specific inventory variant [DELETE]

+ Request Deleting an inventory variant (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: WKpZFJaAg-nmaK5pRaWpoA
        Token-Type: Bearer
        Client: d-_INltgCRzk7mhXsEeFFw
        Expiry: 1519912502
        Uid: shanel_grant@lynch.info

+ Response 204 ()

    + Headers

        access-token: WKpZFJaAg-nmaK5pRaWpoA
        token-type: Bearer
        client: d-_INltgCRzk7mhXsEeFFw
        expiry: 1519912502
        uid: shanel_grant@lynch.info

### Get a specific inventory variant [GET]

+ Request Getting an inventory variant (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: cHgXezoAi6818bOiVze-EQ
        Token-Type: Bearer
        Client: KdZ5j2w8kXHVgYTIwB1jSQ
        Expiry: 1519912501
        Uid: penelope@fahey.com

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: cHgXezoAi6818bOiVze-EQ
        token-type: Bearer
        client: KdZ5j2w8kXHVgYTIwB1jSQ
        expiry: 1519912501
        uid: penelope@fahey.com

    + Body

        {
          "id": "cbddd179-e838-46cb-951c-f6323c545155",
          "quantity": 510,
          "inventory_id": "bfc46d22-a004-45ae-be83-d94f7e02e50b",
          "variant_id": "4766e46d-de8c-4d46-beeb-9974abeaab6f",
          "created_at": "2018-02-01T13:55:01.925Z",
          "updated_at": "2018-02-01T13:55:01.925Z"
        }

### Update an specific inventory variant [PATCH]

+ Request Updating an inventory variant (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: 2qSmBXe4y-Zz9SSnE0Y3Zg
        Token-Type: Bearer
        Client: KsoX9KMuwGurQTDYrb-u0Q
        Expiry: 1519912502
        Uid: lavina.quitzon@schamberger.name

    + Body

        {
          "inventory_variant": {
            "quantity": 12
          }
        }

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: 2qSmBXe4y-Zz9SSnE0Y3Zg
        token-type: Bearer
        client: KsoX9KMuwGurQTDYrb-u0Q
        expiry: 1519912502
        uid: lavina.quitzon@schamberger.name

    + Body

        {
          "id": "cd67dfb6-5a51-4f0a-aa71-2eee532ee0b0",
          "inventory_id": "e2ebbaea-e0a8-428b-9ef4-f874ed2e39fd",
          "quantity": 12,
          "variant_id": "d4a6c388-1ce4-47fe-a6fc-91862c366e17",
          "created_at": "2018-02-01T13:55:02.152Z",
          "updated_at": "2018-02-01T13:55:02.316Z"
        }

# Group Manufacturers

## Manufacturers collection [/manufacturers]

+ Parameters
  + name (required) - Manufacturer&#39;s name
  + notes - Notes about manufacturer
  + store_id (required) - Manufacturer&#39;s store id

### Create a manufacturer [POST]

+ Request Create a manufacturer (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: uEM4xS6xBaSkXdHGg3wp8A
        Token-Type: Bearer
        Client: caKqU5eQi4lXJ8UYhly0Eg
        Expiry: 1519912502
        Uid: howard@kuvalis.org

    + Body

        {
          "manufacturer": {
            "name": "Beedle the Bard",
            "notes": "77928 Elliot Island",
            "store_id": "36489762-a6ff-40ba-850a-e06005763fab"
          }
        }

+ Response 201 (application/json)

    + Headers

        Content-Type: application/json
        access-token: uEM4xS6xBaSkXdHGg3wp8A
        token-type: Bearer
        client: caKqU5eQi4lXJ8UYhly0Eg
        expiry: 1519912502
        uid: howard@kuvalis.org

    + Body

        {
          "id": "4bec65d1-4106-49bb-b420-ba9450bf39b7",
          "name": "Beedle the Bard",
          "notes": "77928 Elliot Island",
          "store_id": "36489762-a6ff-40ba-850a-e06005763fab",
          "created_at": "2018-02-01T13:55:02.950Z",
          "updated_at": "2018-02-01T13:55:02.950Z"
        }

### Returns all manufacturers [GET]

+ Request List all manufacturers (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: 2xjYMfshR6OKvqWYI3ZVmQ
        Token-Type: Bearer
        Client: l_d7-QWVs-_zhqDUMS8CQQ
        Expiry: 1519912502
        Uid: roderick@gutkowskiwuckert.info

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: 2xjYMfshR6OKvqWYI3ZVmQ
        token-type: Bearer
        client: l_d7-QWVs-_zhqDUMS8CQQ
        expiry: 1519912502
        uid: roderick@gutkowskiwuckert.info

    + Body

        [
          {
            "id": "13f1dffe-b5c1-4bd0-87b4-0e41258f47f4",
            "name": "Pigwidgeon",
            "notes": "3785 Schamberger Forest",
            "store_id": "52c148ee-5436-4d73-b425-5d073bf52419",
            "created_at": "2018-02-01T13:55:02.611Z",
            "updated_at": "2018-02-01T13:55:02.611Z"
          }
        ]

## Single manufacturer [/manufacturers/:id]

+ Parameters
  + name (required) - Manufacturer&#39;s name
  + notes - Notes about manufacturer

### Get a specific manufacturer [GET]

+ Request Getting a manufacturer (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: rhMvZZp8aTcTVHwWMnH3QQ
        Token-Type: Bearer
        Client: gxJ5_rXtHC3ycjfXKkuzCQ
        Expiry: 1519912503
        Uid: imelda_lehner@dooley.name

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: rhMvZZp8aTcTVHwWMnH3QQ
        token-type: Bearer
        client: gxJ5_rXtHC3ycjfXKkuzCQ
        expiry: 1519912503
        uid: imelda_lehner@dooley.name

    + Body

        {
          "id": "9e81f72d-4473-4654-a6b6-51f860f7cf9a",
          "name": "Marcus Belby",
          "notes": "5548 Riley Forks",
          "store_id": "f90f22c8-8748-45c4-85b2-0c8501ce3d69",
          "created_at": "2018-02-01T13:55:02.985Z",
          "updated_at": "2018-02-01T13:55:02.985Z"
        }

### Update a specific manufacturer [PATCH]

+ Request Updating a manufacturer (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: jyewX5M1cUOIjHNlR-cWPA
        Token-Type: Bearer
        Client: HnyXBtCTAvrhb0nrMiKELg
        Expiry: 1519912503
        Uid: weston@cummeratarenner.net

    + Body

        {
          "manufacturer": {
            "name": "Marietta Edgecombe"
          }
        }

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: jyewX5M1cUOIjHNlR-cWPA
        token-type: Bearer
        client: HnyXBtCTAvrhb0nrMiKELg
        expiry: 1519912503
        uid: weston@cummeratarenner.net

    + Body

        {
          "id": "6c44bfb5-5a4b-4d4f-aace-55110303090b",
          "store_id": "a2446bb4-cc90-4a8d-b407-d07f53da0d3d",
          "name": "Marietta Edgecombe",
          "notes": "2946 Anne Walk",
          "created_at": "2018-02-01T13:55:03.172Z",
          "updated_at": "2018-02-01T13:55:03.330Z"
        }

# Group Products

## Products collection [/products]

+ Parameters
  + name (required) - Product&#39;s name
  + category_id (required) - Product&#39;s category id
  + manufacturer_id (required) - Product&#39;s manufacturer id
  + store_id (required) - Product&#39;s store id

### Create a product [POST]

+ Request Create a product (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: IIo1cBpMuhMi5EP26PKnWA
        Token-Type: Bearer
        Client: zvRlfIBEG_m4jpWfyvzVbg
        Expiry: 1519912503
        Uid: dominic_huel@turcotte.info

    + Body

        {
          "product": {
            "name": "Péché Mortel",
            "category_id": "cd96305b-cf9d-4eb6-b634-ca8e4daddb56",
            "manufacturer_id": "0b79f2cd-3bfa-460c-b173-b224a93c604b",
            "store_id": "6046c26d-0999-4893-9a4a-6cd44af60964"
          }
        }

+ Response 201 (application/json)

    + Headers

        Content-Type: application/json
        access-token: IIo1cBpMuhMi5EP26PKnWA
        token-type: Bearer
        client: zvRlfIBEG_m4jpWfyvzVbg
        expiry: 1519912503
        uid: dominic_huel@turcotte.info

    + Body

        {
          "id": "c94eff96-01f9-48c1-96f3-0724f2b1bd89",
          "name": "Péché Mortel",
          "category_id": "cd96305b-cf9d-4eb6-b634-ca8e4daddb56",
          "manufacturer_id": "0b79f2cd-3bfa-460c-b173-b224a93c604b",
          "store_id": "6046c26d-0999-4893-9a4a-6cd44af60964",
          "created_at": "2018-02-01T13:55:03.749Z",
          "updated_at": "2018-02-01T13:55:03.749Z"
        }

### Returns all products [GET]

+ Request List all products (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: xGfZc17YVWyvPT6mcC8xbw
        Token-Type: Bearer
        Client: ZbE0gyPE1xPyZ1a8xCWyRA
        Expiry: 1519912503
        Uid: wilson@harvey.org

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: xGfZc17YVWyvPT6mcC8xbw
        token-type: Bearer
        client: ZbE0gyPE1xPyZ1a8xCWyRA
        expiry: 1519912503
        uid: wilson@harvey.org

    + Body

        [
          {
            "id": "23b384d6-1d5f-406b-b80a-0ddc6615767f",
            "name": "Shakespeare Oatmeal",
            "category_id": "a5a94567-0649-4707-9dcf-6e7f799a9ad5",
            "manufacturer_id": "87b02bd1-41e8-4dc8-b124-03709000d36b",
            "store_id": "491c0775-6c04-4c08-aa3b-7b140d5398a1",
            "created_at": "2018-02-01T13:55:03.386Z",
            "updated_at": "2018-02-01T13:55:03.386Z"
          }
        ]

## Single product [/products/:id]

+ Parameters
  + name (required) - Product&#39;s name
  + category_id (required) - Product&#39;s category id
  + manufacturer_id (required) - Product&#39;s manufacturer id

### Get a specific product [GET]

+ Request Getting a product (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: BFj9BohBCC315kww-__L7w
        Token-Type: Bearer
        Client: YQUqFgQBYpQur8ljsGRCxQ
        Expiry: 1519912503
        Uid: roxanne.williamson@kuhic.com

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: BFj9BohBCC315kww-__L7w
        token-type: Bearer
        client: YQUqFgQBYpQur8ljsGRCxQ
        expiry: 1519912503
        uid: roxanne.williamson@kuhic.com

    + Body

        {
          "id": "e0a9d647-6f99-4039-b83a-3041b16b6e85",
          "name": "Trappistes Rochefort 8",
          "category_id": "79089d3e-0ed8-484b-946b-a2c8bb2e0434",
          "manufacturer_id": "b9231902-b213-4405-9724-0c2197ffba9d",
          "store_id": "cdc69d7a-92be-4ee9-afa1-8d36f5076765",
          "created_at": "2018-02-01T13:55:03.794Z",
          "updated_at": "2018-02-01T13:55:03.794Z"
        }

### Update a specific product [PATCH]

+ Request Updating a product (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: ZJ4urHNvEeNUdnQ4MJtiMA
        Token-Type: Bearer
        Client: IG1-VcJkToWK2_okQ5h_ng
        Expiry: 1519912504
        Uid: celestine.kreiger@mccullough.name

    + Body

        {
          "product": {
            "name": "Samuel Smith’s Oatmeal Stout"
          }
        }

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: ZJ4urHNvEeNUdnQ4MJtiMA
        token-type: Bearer
        client: IG1-VcJkToWK2_okQ5h_ng
        expiry: 1519912504
        uid: celestine.kreiger@mccullough.name

    + Body

        {
          "id": "e11d882e-5e0e-40af-82b0-6289972c82f9",
          "store_id": "5471e734-4771-40f3-a8ce-51fda6f5cc01",
          "name": "Samuel Smith’s Oatmeal Stout",
          "category_id": "332c3223-46a1-4d1c-a3d2-47c396b9b151",
          "manufacturer_id": "23da139b-12c9-44d5-91f3-22c77b671ca7",
          "created_at": "2018-02-01T13:55:04.021Z",
          "updated_at": "2018-02-01T13:55:04.201Z"
        }

# Group Providers

## Providers collection [/providers]

+ Parameters
  + name (required) - Provider&#39;s name
  + notes - Notes about provider
  + store_id (required) - Provider&#39;s store id

### Create a provider [POST]

+ Request Create a provider (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: XVQEArtjUU8rpKuAQHgjRg
        Token-Type: Bearer
        Client: KBebhxiwlgI0_0mYw-8d5w
        Expiry: 1519912504
        Uid: ruthe.walker@auer.io

    + Body

        {
          "provider": {
            "name": "Tammy Gueterman",
            "notes": "9594 Schoen Forge",
            "store_id": "3d64631b-2ac8-4e7f-93e8-620646f0878a"
          }
        }

+ Response 201 (application/json)

    + Headers

        Content-Type: application/json
        access-token: XVQEArtjUU8rpKuAQHgjRg
        token-type: Bearer
        client: KBebhxiwlgI0_0mYw-8d5w
        expiry: 1519912504
        uid: ruthe.walker@auer.io

    + Body

        {
          "id": "e35390d6-e155-4a7a-a3df-6bb6f14a1e3d",
          "name": "Tammy Gueterman",
          "notes": "9594 Schoen Forge",
          "store_id": "3d64631b-2ac8-4e7f-93e8-620646f0878a",
          "created_at": "2018-02-01T13:55:04.599Z",
          "updated_at": "2018-02-01T13:55:04.599Z"
        }

### Returns all providers [GET]

+ Request List all providers (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: ZkWYJegHGn4Nxh_FtSYIvg
        Token-Type: Bearer
        Client: ef35n-Jl6Kgpi_QF8o4f0w
        Expiry: 1519912504
        Uid: guillermo.vonrueden@larkin.net

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: ZkWYJegHGn4Nxh_FtSYIvg
        token-type: Bearer
        client: ef35n-Jl6Kgpi_QF8o4f0w
        expiry: 1519912504
        uid: guillermo.vonrueden@larkin.net

    + Body

        [
          {
            "id": "c63d432f-0ece-433d-abf9-d5864795f048",
            "name": "Squanchy",
            "notes": "544 Huel Rapid",
            "store_id": "25ec6398-db25-426c-a7ae-b197df242bd6",
            "created_at": "2018-02-01T13:55:04.253Z",
            "updated_at": "2018-02-01T13:55:04.253Z"
          }
        ]

## Single provider [/providers/:id]

+ Parameters
  + name (required) - Provider&#39;s name
  + notes - Notes about provider

### Get a specific provider [GET]

+ Request Getting a provider (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: MTkhewqmDqsi9y7R_fiwtg
        Token-Type: Bearer
        Client: bE_EsxDPsep-MOBl_Xakbw
        Expiry: 1519912504
        Uid: wellington@kerluke.com

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: MTkhewqmDqsi9y7R_fiwtg
        token-type: Bearer
        client: bE_EsxDPsep-MOBl_Xakbw
        expiry: 1519912504
        uid: wellington@kerluke.com

    + Body

        {
          "id": "11123311-39a9-4348-af62-1da01085d9ce",
          "name": "Revolio 'Gearhead' Clockberg, Jr.",
          "notes": "347 Jovani Rue",
          "store_id": "ab21f9a2-1477-448d-9531-2ba73bea7548",
          "created_at": "2018-02-01T13:55:04.637Z",
          "updated_at": "2018-02-01T13:55:04.637Z"
        }

### Update a specific provider [PATCH]

+ Request Updating a provider (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: f3FNyQvzxsVOlr7MgSdQgg
        Token-Type: Bearer
        Client: tKCGc71PAEwpIl1-PMpEMg
        Expiry: 1519912504
        Uid: rupert_keler@walsh.co

    + Body

        {
          "provider": {
            "name": "Fart"
          }
        }

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: f3FNyQvzxsVOlr7MgSdQgg
        token-type: Bearer
        client: tKCGc71PAEwpIl1-PMpEMg
        expiry: 1519912504
        uid: rupert_keler@walsh.co

    + Body

        {
          "id": "c13abf3d-27c9-45c1-8e9d-4dfa2efa7ddc",
          "store_id": "98595c94-2e7c-4061-b7c4-508002b037a2",
          "name": "Fart",
          "notes": "79971 Casper Ridges",
          "created_at": "2018-02-01T13:55:04.833Z",
          "updated_at": "2018-02-01T13:55:04.996Z"
        }

# Group Shipping Variants

## Shipping variants collection [/shipping_variants]

+ Parameters
  + shipping_id (required) - Shipping variant&#39;s shipping id
  + variant_id (required) - Shipping variant&#39;s variant id
  + quantity (required) - Shipping variant&#39;s quantity

### Create an shipping variant [POST]

+ Request Create an shipping variant (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: j3V0dH_X41MxwG_jk5IIag
        Token-Type: Bearer
        Client: wEvaMvBjXKq8lnleNMENCg
        Expiry: 1519912505
        Uid: arlie@nikolaus.name

    + Body

        {
          "shipping_variant": {
            "shipping_id": "3f312a21-f7fb-43b2-90c6-b29d972d2a46",
            "variant_id": "8032d84e-51a5-420a-ab6e-3c47abcee993",
            "quantity": 5
          }
        }

+ Response 201 (application/json)

    + Headers

        Content-Type: application/json
        access-token: j3V0dH_X41MxwG_jk5IIag
        token-type: Bearer
        client: wEvaMvBjXKq8lnleNMENCg
        expiry: 1519912505
        uid: arlie@nikolaus.name

    + Body

        {
          "id": "81637d84-b6f9-4e9d-9381-5c641a841f6b",
          "quantity": 5,
          "shipping_id": "3f312a21-f7fb-43b2-90c6-b29d972d2a46",
          "variant_id": "8032d84e-51a5-420a-ab6e-3c47abcee993",
          "created_at": "2018-02-01T13:55:05.542Z",
          "updated_at": "2018-02-01T13:55:05.542Z"
        }

### Returns all shipping_variants [GET]

+ Request List all shipping_variants (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: CMI-gV4coLC6dvzB98jNrQ
        Token-Type: Bearer
        Client: YuRbUOJUN681y7p18A-uqQ
        Expiry: 1519912505
        Uid: otto@heellegros.co

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: CMI-gV4coLC6dvzB98jNrQ
        token-type: Bearer
        client: YuRbUOJUN681y7p18A-uqQ
        expiry: 1519912505
        uid: otto@heellegros.co

    + Body

        [
          {
            "id": "409e75ea-666e-434e-aa2d-483258a2c909",
            "quantity": 277,
            "shipping_id": "426704c4-7134-4f10-ac8b-e0b514ed94eb",
            "variant_id": "8523c470-b01c-4d07-b6d6-2ce216800822",
            "created_at": "2018-02-01T13:55:05.159Z",
            "updated_at": "2018-02-01T13:55:05.159Z"
          }
        ]

## Single shipping variant [/shipping_variants/:id]

+ Parameters
  + quantity (required) - Shipping variant&#39;s quantity

### Delete a specific shipping variant [DELETE]

+ Request Deleting an shipping variant (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: KMDvrcJ7I5bv7MuHakMp8w
        Token-Type: Bearer
        Client: NIs-o1xi6thwHkI8iLrG3w
        Expiry: 1519912506
        Uid: ford.bahringer@ziemannswift.net

+ Response 204 ()

    + Headers

        access-token: KMDvrcJ7I5bv7MuHakMp8w
        token-type: Bearer
        client: NIs-o1xi6thwHkI8iLrG3w
        expiry: 1519912506
        uid: ford.bahringer@ziemannswift.net

### Get a specific shipping variant [GET]

+ Request Getting an shipping variant (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: KlQsh5qaxikystZkgQ7NMw
        Token-Type: Bearer
        Client: FaiEFED7hN58c17SEYQrFA
        Expiry: 1519912505
        Uid: coby@swift.co

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: KlQsh5qaxikystZkgQ7NMw
        token-type: Bearer
        client: FaiEFED7hN58c17SEYQrFA
        expiry: 1519912505
        uid: coby@swift.co

    + Body

        {
          "id": "6506e2ce-21a5-4a38-a3a0-73c67e1656b7",
          "quantity": 536,
          "shipping_id": "6498e80e-c36f-48e1-a1da-329d2c667e74",
          "variant_id": "d42e54c0-e147-4f9b-8944-dd89812a26dd",
          "created_at": "2018-02-01T13:55:05.614Z",
          "updated_at": "2018-02-01T13:55:05.614Z"
        }

### Update an specific shipping variant [PATCH]

+ Request Updating an shipping variant (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: WPF_jz0FmghTAl-uvDOoOw
        Token-Type: Bearer
        Client: vxj7vW_b7sIkq5rl_SJ5ew
        Expiry: 1519912505
        Uid: wayne.shanahan@rolfson.com

    + Body

        {
          "shipping_variant": {
            "quantity": 12
          }
        }

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: WPF_jz0FmghTAl-uvDOoOw
        token-type: Bearer
        client: vxj7vW_b7sIkq5rl_SJ5ew
        expiry: 1519912505
        uid: wayne.shanahan@rolfson.com

    + Body

        {
          "id": "6889a4fe-5916-4054-a8c3-52f65e422d14",
          "shipping_id": "a781b3dc-29d5-45da-86ff-5c848e9831f0",
          "quantity": 12,
          "variant_id": "7cbca977-da90-4cdd-958a-4730efa91c3d",
          "created_at": "2018-02-01T13:55:05.835Z",
          "updated_at": "2018-02-01T13:55:05.990Z"
        }

# Group Shippings

## Shippings collection [/shippings]

+ Parameters
  + store_id (required) - Shipping&#39;s store id

### Create a shipping [POST]

+ Request Create a shipping (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: WxHsK3XkAiyl7WiGQoUSIg
        Token-Type: Bearer
        Client: lIZYeqVg238d5J7wWM15UA
        Expiry: 1519912506
        Uid: marisol@rennerwyman.org

    + Body

        {
          "shipping": {
            "store_id": "9e3f7cd0-adcf-4cc9-b9ce-04f30e42851b"
          }
        }

+ Response 201 (application/json)

    + Headers

        Content-Type: application/json
        access-token: WxHsK3XkAiyl7WiGQoUSIg
        token-type: Bearer
        client: lIZYeqVg238d5J7wWM15UA
        expiry: 1519912506
        uid: marisol@rennerwyman.org

    + Body

        {
          "id": "4cd6e099-0242-49b1-9e69-a198b2d54846",
          "locked_at": null,
          "store_id": "9e3f7cd0-adcf-4cc9-b9ce-04f30e42851b",
          "created_at": "2018-02-01T13:55:06.599Z",
          "updated_at": "2018-02-01T13:55:06.599Z"
        }

### Returns all shippings [GET]

+ Request List all shippings (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: eVM-iUWurEzQXWR1jzpxaQ
        Token-Type: Bearer
        Client: Yaeqp7IYwfbQA1n8EJHsmw
        Expiry: 1519912506
        Uid: gladyce_rice@kub.io

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: eVM-iUWurEzQXWR1jzpxaQ
        token-type: Bearer
        client: Yaeqp7IYwfbQA1n8EJHsmw
        expiry: 1519912506
        uid: gladyce_rice@kub.io

    + Body

        [
          {
            "id": "654b581e-fc58-4546-8021-be5639be5ddf",
            "locked_at": null,
            "store_id": "9961e181-afa4-465d-8506-7c7a31d10618",
            "created_at": "2018-02-01T13:55:06.264Z",
            "updated_at": "2018-02-01T13:55:06.264Z"
          }
        ]

## Single shipping [/shippings/:id]

### Delete a specific shipping [DELETE]

+ Request Deleting a shipping (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: ZX64JYgY1oX4lCPudX-EoQ
        Token-Type: Bearer
        Client: FaBvL72IuW4GC-MZ3G6X1A
        Expiry: 1519912506
        Uid: eugenia@casper.net

+ Response 204 ()

    + Headers

        access-token: ZX64JYgY1oX4lCPudX-EoQ
        token-type: Bearer
        client: FaBvL72IuW4GC-MZ3G6X1A
        expiry: 1519912506
        uid: eugenia@casper.net

### Get a specific shipping [GET]

+ Request Getting a shipping (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: prQk47O_o6F10-uGfdO26g
        Token-Type: Bearer
        Client: r9acQhIscby_tnsI6JwcrA
        Expiry: 1519912506
        Uid: sylvester_bernier@block.io

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: prQk47O_o6F10-uGfdO26g
        token-type: Bearer
        client: r9acQhIscby_tnsI6JwcrA
        expiry: 1519912506
        uid: sylvester_bernier@block.io

    + Body

        {
          "id": "8b2f607a-7930-4f3a-824c-8ed6dbebe7da",
          "locked_at": null,
          "store_id": "c38990f8-2308-48c7-aadc-363993fa2186",
          "created_at": "2018-02-01T13:55:06.636Z",
          "updated_at": "2018-02-01T13:55:06.636Z"
        }

## Single shipping [/shippings/:id/lock]

### Lock a specific shipping [PATCH]

+ Request Locking a shipping (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: qN2BVILVSnjkMtKQ9JCHlw
        Token-Type: Bearer
        Client: Dx8UWEY8OxpA7oE88kl42Q
        Expiry: 1519912507
        Uid: kelley@hayes.net

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: qN2BVILVSnjkMtKQ9JCHlw
        token-type: Bearer
        client: Dx8UWEY8OxpA7oE88kl42Q
        expiry: 1519912507
        uid: kelley@hayes.net

    + Body

        {
          "id": "6308aadc-e013-4919-ba40-cc812db25b4c",
          "store_id": "1d94e833-edf7-4567-a881-a4ba96ca1fd5",
          "locked_at": "2018-02-01T13:55:07.173Z",
          "created_at": "2018-02-01T13:55:07.021Z",
          "updated_at": "2018-02-01T13:55:07.174Z"
        }

# Group Stock Backup Variants

## Single stock backup variant [/stock_backup_variants/:id]

### Get a specific stock backup variant [GET]

+ Request Getting a stock backup variant (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: mAYasxYrmwlK6pPXPRTQEQ
        Token-Type: Bearer
        Client: NVsflySOwfywP0qQ099kAA
        Expiry: 1519912507
        Uid: aida.hermiston@reichert.name

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: mAYasxYrmwlK6pPXPRTQEQ
        token-type: Bearer
        client: NVsflySOwfywP0qQ099kAA
        expiry: 1519912507
        uid: aida.hermiston@reichert.name

    + Body

        {
          "id": "6d3ef48c-eeac-4036-b4e6-19ed42ada605",
          "quantity": 0,
          "stock_backup_id": "a19ba2da-c08f-46f4-9f66-77528ddc3071",
          "variant_id": "f01daaba-c24f-4dba-b833-cb33fba147a1",
          "created_at": "2018-02-01T13:55:07.531Z",
          "updated_at": "2018-02-01T13:55:07.531Z"
        }

## Stock backup variants collection [/stock_backup_variants]

### Returns all stock backup_variants [GET]

+ Request List all stock backup_variants (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: ILDBt08MHAmQp5b46f1fmQ
        Token-Type: Bearer
        Client: pI7RLzGJVHp8o6YEhNPEiQ
        Expiry: 1519912507
        Uid: mallie@macgyver.net

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: ILDBt08MHAmQp5b46f1fmQ
        token-type: Bearer
        client: pI7RLzGJVHp8o6YEhNPEiQ
        expiry: 1519912507
        uid: mallie@macgyver.net

    + Body

        [
          {
            "id": "fb152137-2374-43a8-abf4-5f14f4f02c6d",
            "quantity": 0,
            "stock_backup_id": "2a2f15cf-0ba8-4984-b342-3dfcd8dab6cf",
            "variant_id": "be11ca2f-253a-43b9-9db3-d1096589772a",
            "created_at": "2018-02-01T13:55:07.309Z",
            "updated_at": "2018-02-01T13:55:07.309Z"
          }
        ]

# Group Stock Backups

## Single stock_backup [/stock_backups/:id]

### Get a specific stock backup [GET]

+ Request Getting a stock_backup (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: 4GaQY91w3uPruFwsTFIieg
        Token-Type: Bearer
        Client: qWSY9ZVwA0LqAFod4UE6YQ
        Expiry: 1519912507
        Uid: savannah@ruel.co

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: 4GaQY91w3uPruFwsTFIieg
        token-type: Bearer
        client: qWSY9ZVwA0LqAFod4UE6YQ
        expiry: 1519912507
        uid: savannah@ruel.co

    + Body

        {
          "id": "b7507221-2531-4c1c-88ef-c82b19b20a7b",
          "store_id": "61de57ab-9d8b-43f3-a812-1771b58fe5ab",
          "created_at": "2018-02-01T13:55:07.907Z",
          "updated_at": "2018-02-01T13:55:07.907Z"
        }

## Stock backups collection [/stock_backups]

### Returns all stock backups [GET]

+ Request List all stock backups (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: mLU58MfIGdXJcKUd_BmQkA
        Token-Type: Bearer
        Client: AfGlEFc9Rk3HF0NEF9VTjA
        Expiry: 1519912507
        Uid: laurine@klockozboncak.net

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: mLU58MfIGdXJcKUd_BmQkA
        token-type: Bearer
        client: AfGlEFc9Rk3HF0NEF9VTjA
        expiry: 1519912507
        uid: laurine@klockozboncak.net

    + Body

        [
          {
            "id": "29a917ad-df88-4466-a693-8925c88fa19d",
            "store_id": "11b04752-6529-4683-b738-2873dbdc1dcd",
            "created_at": "2018-02-01T13:55:07.726Z",
            "updated_at": "2018-02-01T13:55:07.726Z"
          }
        ]

# Group Store Memberships

## Store memberships collection [/store_memberships]

+ Parameters
  + user_id (required) - Membership&#39;s user
  + store_id (required) - Membership&#39;s store
  + role (required) - Membership&#39;s role (regular, admin, owner)

### Create a store membership [POST]

+ Request Create a store membership (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: Q6bqq4lugIfbD9rUghTXjA
        Token-Type: Bearer
        Client: B-bj0YQzsXUtwz_m9hWldA
        Expiry: 1519912508
        Uid: arjun_kreiger@hoeger.info

    + Body

        {
          "store_membership": {
            "user_id": "4b00d6da-1d4d-4cce-b4b1-9c795b77ba10",
            "store_id": "22fe46e4-0486-4a6f-b190-290570abc120",
            "role": "regular"
          }
        }

+ Response 201 (application/json)

    + Headers

        Content-Type: application/json
        access-token: Q6bqq4lugIfbD9rUghTXjA
        token-type: Bearer
        client: B-bj0YQzsXUtwz_m9hWldA
        expiry: 1519912508
        uid: arjun_kreiger@hoeger.info

    + Body

        {
          "id": "419ee045-2314-4fb7-a8cb-11d24e79c82c",
          "store_id": "22fe46e4-0486-4a6f-b190-290570abc120",
          "user_id": "4b00d6da-1d4d-4cce-b4b1-9c795b77ba10",
          "role": "regular",
          "created_at": "2018-02-01T13:55:08.454Z",
          "updated_at": "2018-02-01T13:55:08.454Z"
        }

### Returns all store memberships [GET]

+ Request List all store memberships (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: WTG6DooyI4vUWcDyISWQJQ
        Token-Type: Bearer
        Client: Q2LHulZt4muS6sFFtUPwJw
        Expiry: 1519912508
        Uid: aliya@kulasmante.biz

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: WTG6DooyI4vUWcDyISWQJQ
        token-type: Bearer
        client: Q2LHulZt4muS6sFFtUPwJw
        expiry: 1519912508
        uid: aliya@kulasmante.biz

    + Body

        [
          {
            "id": "a66eaa2e-c58a-47b0-beb4-ba0e2b13ed35",
            "store_id": "8926bdde-8114-4dfb-88d1-d126f8574555",
            "user_id": "973322a2-ef9f-40ad-a0e6-2c6ef0b6a908",
            "role": "admin",
            "created_at": "2018-02-01T13:55:08.083Z",
            "updated_at": "2018-02-01T13:55:08.083Z"
          }
        ]

## Single store membership [/store_memberships/:id]

+ Parameters
  + role (required) - Membership&#39;s role (regular, admin, owner)

### Delete a specific store membership [DELETE]

+ Request Deleting a store membership (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: L3fkqXCr1xTeEMii-Su1gA
        Token-Type: Bearer
        Client: NOdfcVOsap7P_LLkY4yzuQ
        Expiry: 1519912508
        Uid: karolann@hodkiewicz.name

+ Response 204 ()

    + Headers

        access-token: L3fkqXCr1xTeEMii-Su1gA
        token-type: Bearer
        client: NOdfcVOsap7P_LLkY4yzuQ
        expiry: 1519912508
        uid: karolann@hodkiewicz.name

### Get a specific store membership [GET]

+ Request Getting a store membership (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: YJoFYTD9ud2ST1MsEmvPag
        Token-Type: Bearer
        Client: Rnki2xWmVZMHZ0pMmZ27ww
        Expiry: 1519912508
        Uid: mikel.schulist@kuvalis.org

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: YJoFYTD9ud2ST1MsEmvPag
        token-type: Bearer
        client: Rnki2xWmVZMHZ0pMmZ27ww
        expiry: 1519912508
        uid: mikel.schulist@kuvalis.org

    + Body

        {
          "id": "8b8b46d0-7382-4294-a77a-bee8e8b933bd",
          "store_id": "6e45711e-f3aa-4881-be5c-388c9b357737",
          "user_id": "afbbc3cc-9e1c-4b12-b74c-219b7c00347a",
          "role": "owner",
          "created_at": "2018-02-01T13:55:08.501Z",
          "updated_at": "2018-02-01T13:55:08.501Z"
        }

### Update a specific store membership [PATCH]

+ Request Updating a store membership (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: W3gscD2sLeH3vqVFkMdd4A
        Token-Type: Bearer
        Client: SMGqvkY6qa466TvP_q6kKw
        Expiry: 1519912508
        Uid: dan@luettgen.biz

    + Body

        {
          "store_membership": {
            "role": "admin"
          }
        }

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: W3gscD2sLeH3vqVFkMdd4A
        token-type: Bearer
        client: SMGqvkY6qa466TvP_q6kKw
        expiry: 1519912508
        uid: dan@luettgen.biz

    + Body

        {
          "id": "1bb07d9e-a747-40d0-ad43-e4be91e106c1",
          "store_id": "2b8edc00-303c-4f54-afe6-f7abd053faf8",
          "role": "admin",
          "user_id": "502b5881-5653-40ac-8922-56c151bcd855",
          "created_at": "2018-02-01T13:55:08.696Z",
          "updated_at": "2018-02-01T13:55:08.696Z"
        }

# Group Stores

## Stores collection [/stores]

+ Parameters
  + name (required) - Store&#39;s name
  + address - Store&#39;s address
  + country (required) - Store&#39;s country
  + key (required) - Store&#39;s key

### Create a store [POST]

+ Request Create a store (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: 9ZbTQ4qYMDO-Iq1mF9UOFQ
        Token-Type: Bearer
        Client: bvFGJbIK29E28zq8esmndA
        Expiry: 1519912509
        Uid: marshall.herzog@sporer.biz

    + Body

        {
          "store": {
            "name": "Geonosis",
            "address": "333 Gerhold Court",
            "country": "GU",
            "key": "geonosis-89"
          }
        }

+ Response 201 (application/json)

    + Headers

        Content-Type: application/json
        access-token: 9ZbTQ4qYMDO-Iq1mF9UOFQ
        token-type: Bearer
        client: bvFGJbIK29E28zq8esmndA
        expiry: 1519912509
        uid: marshall.herzog@sporer.biz

    + Body

        {
          "id": "644d46e7-18b7-4eb0-ae7e-62d41de4cff8",
          "key": "geonosis-89",
          "name": "Geonosis",
          "address": "333 Gerhold Court",
          "country": "GU",
          "created_at": "2018-02-01T13:55:09.413Z",
          "updated_at": "2018-02-01T13:55:09.413Z"
        }

### Returns all stores [GET]

+ Request List all stores (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: CEzTK1nO2fXzXrsm7NUqHQ
        Token-Type: Bearer
        Client: B2clkQHeqXVangIydoll5w
        Expiry: 1519912509
        Uid: amely@mcdermott.net

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: CEzTK1nO2fXzXrsm7NUqHQ
        token-type: Bearer
        client: B2clkQHeqXVangIydoll5w
        expiry: 1519912509
        uid: amely@mcdermott.net

    + Body

        [
          {
            "id": "de1104ce-31cf-40f5-9bdf-c537e7c9f430",
            "key": "mustafar-88",
            "name": "Mustafar",
            "address": "4736 Kshlerin Views",
            "country": "ET",
            "created_at": "2018-02-01T13:55:09.069Z",
            "updated_at": "2018-02-01T13:55:09.069Z"
          }
        ]

## Single store [/stores/:id]

+ Parameters
  + name (required) - Store&#39;s name
  + address - Store&#39;s address
  + country (required) - Store&#39;s country

### Get a specific store [GET]

+ Request Getting a store (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: w6pbrMT6eFVOr00xWF2ELg
        Token-Type: Bearer
        Client: yldBGDooj1ydu911mv4gSw
        Expiry: 1519912509
        Uid: joanne@kutch.org

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: w6pbrMT6eFVOr00xWF2ELg
        token-type: Bearer
        client: yldBGDooj1ydu911mv4gSw
        expiry: 1519912509
        uid: joanne@kutch.org

    + Body

        {
          "id": "cdf839f7-5f0e-4fa5-bde5-0578ed265b0f",
          "key": "geonosis-91",
          "name": "Geonosis",
          "address": "713 Schmitt Knoll",
          "country": "MC",
          "created_at": "2018-02-01T13:55:09.436Z",
          "updated_at": "2018-02-01T13:55:09.436Z"
        }

### Update a specific store [PATCH]

+ Request Updating a store (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: DpaiqjUxoul0Ewg94yNdKQ
        Token-Type: Bearer
        Client: oOEW9cC-zhuKESLz42kPZA
        Expiry: 1519912509
        Uid: tiffany@damoreleannon.info

    + Body

        {
          "store": {
            "name": "Utapau"
          }
        }

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: DpaiqjUxoul0Ewg94yNdKQ
        token-type: Bearer
        client: oOEW9cC-zhuKESLz42kPZA
        expiry: 1519912509
        uid: tiffany@damoreleannon.info

    + Body

        {
          "id": "1b442141-0b32-4a6e-8155-388e7b11a6d6",
          "name": "Utapau",
          "country": "AW",
          "key": "bespin-92",
          "address": "941 Howard Burgs",
          "created_at": "2018-02-01T13:55:09.614Z",
          "updated_at": "2018-02-01T13:55:09.782Z"
        }

# Group Variant Attributes

## Variant Attributes collection [/variant_attributes]

+ Parameters
  + value (required) - Variant Attribute&#39;s value
  + custom_attribute_id (required) - Variant Attribute&#39;s custom attribute id
  + variant_id (required) - Variant Attribute&#39;s variant id

### Create a variant attribute [POST]

+ Request Create a variant attribute (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: KNTGiwSRj7cDtjC8ch4v3Q
        Token-Type: Bearer
        Client: C7xQkrLHNCvc5zBRheZB-g
        Expiry: 1519912510
        Uid: kyler@waters.co

    + Body

        {
          "variant_attribute": {
            "value": "Black malt",
            "custom_attribute_id": "350954a0-733d-4c78-9f3f-06fda78e3eb9",
            "variant_id": "f1ad1681-5b84-4da9-8038-325f44421eaf"
          }
        }

+ Response 201 (application/json)

    + Headers

        Content-Type: application/json
        access-token: KNTGiwSRj7cDtjC8ch4v3Q
        token-type: Bearer
        client: C7xQkrLHNCvc5zBRheZB-g
        expiry: 1519912510
        uid: kyler@waters.co

    + Body

        {
          "id": "71623be5-b008-4212-8446-cb7d4d5c2912",
          "value": "Black malt",
          "variant_id": "f1ad1681-5b84-4da9-8038-325f44421eaf",
          "custom_attribute_id": "350954a0-733d-4c78-9f3f-06fda78e3eb9",
          "created_at": "2018-02-01T13:55:10.298Z",
          "updated_at": "2018-02-01T13:55:10.298Z"
        }

### Returns all variant_attributes [GET]

+ Request List all variant attributes (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: VVyugu9XjEP0B-9Ru-HBMA
        Token-Type: Bearer
        Client: 8Ho2-RCVHm92wAL4oZ3tRw
        Expiry: 1519912509
        Uid: abdullah@murphy.org

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: VVyugu9XjEP0B-9Ru-HBMA
        token-type: Bearer
        client: 8Ho2-RCVHm92wAL4oZ3tRw
        expiry: 1519912509
        uid: abdullah@murphy.org

    + Body

        [
          {
            "id": "47230452-9ad9-483e-b3a7-f46f7508f6e4",
            "value": "Caramel",
            "variant_id": "19788982-c880-4153-a0ab-3bf06eeb5f56",
            "custom_attribute_id": "09f67585-8528-4a72-84b0-240ca12650e6",
            "created_at": "2018-02-01T13:55:09.919Z",
            "updated_at": "2018-02-01T13:55:09.919Z"
          }
        ]

## Single variant attribute [/variant_attributes/:id]

+ Parameters
  + value (required) - Variant Attribute&#39;s value

### Delete a specific variant attribute [DELETE]

+ Request Deleting a variant attribute (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: wmuRqwHqwpiLYDdvbwQOYA
        Token-Type: Bearer
        Client: Crl7Sww-J4xtQjhJniaTwg
        Expiry: 1519912510
        Uid: sallie@reingerhowe.io

+ Response 204 ()

    + Headers

        access-token: wmuRqwHqwpiLYDdvbwQOYA
        token-type: Bearer
        client: Crl7Sww-J4xtQjhJniaTwg
        expiry: 1519912510
        uid: sallie@reingerhowe.io

### Get a specific variant attribute [GET]

+ Request Getting a variant attribute (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: 3Q167psGy1aAhhRh5QrRlA
        Token-Type: Bearer
        Client: TB0dhfh7u6ZUOwpQbrwIig
        Expiry: 1519912510
        Uid: kavon@bailey.name

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: 3Q167psGy1aAhhRh5QrRlA
        token-type: Bearer
        client: TB0dhfh7u6ZUOwpQbrwIig
        expiry: 1519912510
        uid: kavon@bailey.name

    + Body

        {
          "id": "2253aec8-4353-49d0-b3d0-3910b9c336d1",
          "value": "Wheat mal",
          "variant_id": "f38c300e-f51a-445b-8965-3ed363369175",
          "custom_attribute_id": "0ca470a8-21d5-45f9-8447-5a6d59b3c5d3",
          "created_at": "2018-02-01T13:55:10.381Z",
          "updated_at": "2018-02-01T13:55:10.381Z"
        }

### Update a specific variant attribute [PATCH]

+ Request Updating a variant_attribute (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: _MKJ01-ACojMQhTKE46hXw
        Token-Type: Bearer
        Client: vvqHU0EzSMTcDUVZpi1LZA
        Expiry: 1519912510
        Uid: cory.greenholt@erdman.net

    + Body

        {
          "variant_attribute": {
            "value": "Vienna"
          }
        }

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: _MKJ01-ACojMQhTKE46hXw
        token-type: Bearer
        client: vvqHU0EzSMTcDUVZpi1LZA
        expiry: 1519912510
        uid: cory.greenholt@erdman.net

    + Body

        {
          "id": "04cafb19-753e-41e8-9187-8dac4b7e1bc9",
          "variant_id": "da9a8dae-d876-4ef3-a4b9-b6d4e2816144",
          "value": "Vienna",
          "custom_attribute_id": "f1459c34-4ff3-4f86-8eed-a759670fa43e",
          "created_at": "2018-02-01T13:55:10.620Z",
          "updated_at": "2018-02-01T13:55:10.830Z"
        }

# Group Variants

## Variants collection [/variants]

+ Parameters
  + original_barcode (required) - Variant&#39;s original barcode
  + buying_price (required) - Variant&#39;s buying price
  + tax_free_price (required) - Variant&#39;s tax free price
  + ratio (required) - Variant&#39;s ratio
  + product_id (required) - Variant&#39;s product id
  + provider_id (required) - Variant&#39;s provider id
  + default (required) - (bool) Is it the product default variant ?

### Create a variant [POST]

+ Request Create a variant (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: m3guA0SMnehGvVcqSx-Tjg
        Token-Type: Bearer
        Client: 7E6lsW85zmDbMgPB6o_Q4g
        Expiry: 1519912511
        Uid: hertha.becker@mckenzie.name

    + Body

        {
          "variant": {
            "original_barcode": "9259975231",
            "buying_price": "91.98",
            "tax_free_price": 165.56400000000002,
            "ratio": "50.42",
            "product_id": "f281afed-8cb6-490e-b21e-9d8c8cfce41f",
            "provider_id": "d0522332-8caf-4637-be89-aecbb91b0ffc",
            "default": false
          }
        }

+ Response 201 (application/json)

    + Headers

        Content-Type: application/json
        access-token: m3guA0SMnehGvVcqSx-Tjg
        token-type: Bearer
        client: 7E6lsW85zmDbMgPB6o_Q4g
        expiry: 1519912511
        uid: hertha.becker@mckenzie.name

    + Body

        {
          "id": "6682c2d7-0ba0-4733-9f38-307d198638f4",
          "original_barcode": "9259975231",
          "barcode": "000009259975231",
          "buying_price": 91.98,
          "tax_free_price": 165.56400000000002,
          "ratio": 50.42,
          "quantity": 0,
          "default": false,
          "product_id": "f281afed-8cb6-490e-b21e-9d8c8cfce41f",
          "provider_id": "d0522332-8caf-4637-be89-aecbb91b0ffc",
          "created_at": "2018-02-01T13:55:11.536Z",
          "updated_at": "2018-02-01T13:55:11.536Z"
        }

### Returns all variants [GET]

+ Request List all variants (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: U7Ye9gR90l5KcH8RX0Q6QQ
        Token-Type: Bearer
        Client: fBo-Tmfr_q7w8I2w7tHIDw
        Expiry: 1519912511
        Uid: toby@adamsfriesen.info

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: U7Ye9gR90l5KcH8RX0Q6QQ
        token-type: Bearer
        client: fBo-Tmfr_q7w8I2w7tHIDw
        expiry: 1519912511
        uid: toby@adamsfriesen.info

    + Body

        [
          {
            "id": "4e000fe5-0f1e-4cfc-a117-cfdd1ae34f6f",
            "original_barcode": "5366846243",
            "barcode": "000005366846243",
            "buying_price": 11.01,
            "tax_free_price": 19.818,
            "ratio": 31.74,
            "quantity": 0,
            "default": false,
            "product_id": "0aafc941-3533-4c8f-b9df-ecb5a4cc236f",
            "provider_id": "55d4b68d-8361-4c65-9d47-71745323f403",
            "created_at": "2018-02-01T13:55:11.166Z",
            "updated_at": "2018-02-01T13:55:11.166Z"
          }
        ]

## Single variant [/variants/:id]

+ Parameters
  + buying_price (required) - Variant&#39;s buying price
  + tax_free_price (required) - Variant&#39;s tax free price
  + ratio (required) - Variant&#39;s ratio
  + default (required) - (bool) Is it the product default variant ?

### Get a specific variant [GET]

+ Request Getting a variant (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: Inw5D-UIlcig56O81DArhA
        Token-Type: Bearer
        Client: 5lA6yX-rKRZzcJthYI8oNQ
        Expiry: 1519912511
        Uid: katelyn_white@kshlerinkertzmann.co

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: Inw5D-UIlcig56O81DArhA
        token-type: Bearer
        client: 5lA6yX-rKRZzcJthYI8oNQ
        expiry: 1519912511
        uid: katelyn_white@kshlerinkertzmann.co

    + Body

        {
          "id": "0cfb611d-3a83-490d-bd72-1da451e8583f",
          "original_barcode": "3297900370",
          "barcode": "000003297900370",
          "buying_price": 99.27,
          "tax_free_price": 178.686,
          "ratio": 41.64,
          "quantity": 0,
          "default": false,
          "product_id": "16fb8508-d385-4efa-9f8d-7f9218054bff",
          "provider_id": "a72a96c5-01c2-41eb-b572-12f8db3069f0",
          "created_at": "2018-02-01T13:55:11.601Z",
          "updated_at": "2018-02-01T13:55:11.601Z"
        }

### Update a specific variant [PATCH]

+ Request Updating a variant (application/json)

    + Headers

        Accept: application/json
        Content-Type: application/json
        Access-Token: Le7Kuht8C0ZO0-6FnkfEcQ
        Token-Type: Bearer
        Client: QKEat5_6y-XQ1RZCyL0_NA
        Expiry: 1519912511
        Uid: dandre@hintzhackett.co

    + Body

        {
          "variant": {
            "ratio": 97.84
          }
        }

+ Response 200 (application/json)

    + Headers

        Content-Type: application/json
        access-token: Le7Kuht8C0ZO0-6FnkfEcQ
        token-type: Bearer
        client: QKEat5_6y-XQ1RZCyL0_NA
        expiry: 1519912511
        uid: dandre@hintzhackett.co

    + Body

        {
          "id": "ec619fb6-ba18-4ad3-aff5-f871a2044890",
          "product_id": "dd0255c1-3d66-4d5c-a9cd-15d89b46221f",
          "ratio": 97.84,
          "provider_id": "2c111a6a-6b50-4c44-8c95-9529302c7e40",
          "barcode": "000005640239174",
          "buying_price": 95.15,
          "original_barcode": "5640239174",
          "quantity": 0,
          "tax_free_price": 171.27,
          "default": false,
          "created_at": "2018-02-01T13:55:11.814Z",
          "updated_at": "2018-02-01T13:55:12.001Z"
        }
